name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
permissions:
  contents: write
jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v5
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Install Devbox packages 
            uses: jetify-com/devbox-install-action@v0.14.0
          - name: Run unit test
            run: timeout 1m ./test.sh
          - name: Run full test
            run: timeout 1m ./full-test.sh
