name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v5
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: create tmp dir
            run: mkdir /tmp
          - name: Run unit test
            run: ./unit-test.sh
          - name: Run full test
            run: ./full-test.sh

